plugins {
    alias(libs.plugins.android.application)
}

ext {
    appname = "com.rhino.vpnapp" //"com.android.vpnapp"
    compileSDK = 37
    minSDK = 24
    targetSDK = 36
}

android {
    namespace "com.rhino.vpnapp"
    compileSdkVersion compileSDK

    defaultConfig {
        applicationId "com.rhino.vpnapp"
        minSdk minSDK
        targetSdk targetSDK
        versionCode 18
        versionName "5.0.0.5"
        configurations.configureEach {
            resolutionStrategy { force 'androidx.core:core-ktx:1.13.0' }
        }

        buildConfigField 'boolean', "ADS_SHOWN", "true"//true or false
        buildConfigField 'String', "AD_NETWORK", '"startapp"' // "admob" or "facebook" or "startapp"

        //Test Ads Key
        resValue 'string', "main_app_id", "ca-app-pub-4324936595385675~4572282704"
        resValue 'string', "banner_app_id", "ca-app-pub-4324936595385675/3164794938"
        resValue 'string', "interstitial_app_id", "ca-app-pub-4324936595385675/5025842372"
        resValue 'string', "native_app_id", "ca-app-pub-4324936595385675/7790435654"
        resValue 'string', "app_open_id", "ca-app-pub-4324936595385675/1565109510"

        // Facebook Ads Keys
        resValue 'string', "fb_banner_id", "27505075835792910_27505364145764079"
        resValue 'string', "fb_interstitial_id", "27505075835792910_27505368502430310"
        resValue 'string', "fb_native_id", "27505075835792910_27505371569096670"

        resValue 'string', "startapp_app_id", "205942013"

        resValue 'string', 'feedback_email', "manish.mg698@gmail.com"
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
    bundle {
        abi {
            enableSplit false
        }
    }
    buildFeatures {
        buildConfig true
        aidl true
    }
//    lint {
//        baseline = file("lint-baseline.xml")
//    }
    lint {
        abortOnError(false)
        checkReleaseBuilds(false)
        ignoreWarnings(true)
        disable 'OldTargetApi', 'GradleDependency', 'GradleDynamicVersion'
    }

    configurations.configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == "org.jetbrains.kotlin") {
                details.useVersion "1.8.22"
            }
        }
    }
}

dependencies {
    implementation project(':nativetemplates')
    implementation files('libs/achartengine-1.2.0.jar')
    implementation project(':rating-library')

    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.constraint)
    implementation(libs.viewpager2)
    implementation(libs.circleindicator)
    implementation(libs.lottie)
    implementation(libs.circleimageview)
    implementation(libs.googleads)
    implementation(libs.gson)
    implementation(libs.webkit)
    implementation(libs.materialDialog)
    implementation(libs.ktx)
    implementation(libs.localbroadcastmanager)
    implementation(libs.runtime)
    implementation(libs.lifeextensions)
    implementation(libs.crypto)
    implementation(libs.fastscroll)
    implementation(libs.openssl)
    implementation(libs.glide)
    implementation(libs.facebookads)
    implementation(libs.startappads)
    implementation(libs.annotation)
    implementation "androidx.core:core:1.13.0" // or higher
}
